### ISSUE TITLE
hOW tO dOwNLoAd! 

### ISSUE THREAD

**Issue by Efligonn** [simonmeusel/alan-source#3]
In the discription how to use offline its not said that you have to unzip the folder before open index.html. Please change that, its an issue for people new to such things.

**Comment by simonmeusel** [comment]
That's already in the description!

**Comment by simonmeusel** [comment]
https://github.com/simonmeusel/alan

**Comment by Efligonn** [comment]
Now its said i have to i unzip the download... that could in some way confuse people because they have to unzip the folder they downloaded... how should they know about what to unzip exactly?

**Comment by Efligonn** [comment]
this issue have not been fixed for at least 3 minutes now... what are you doing??
